// frontend/src/styles.js
export const buttonGroup = 'flex space-x-2';
export const buttonPrimary = 'w-full p-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors';
export const buttonSecondary = 'w-full p-2 bg-gray-600 text-white rounded hover:bg-gray-700 transition-colors';
export const centered = 'text-center';
export const centeredButton = 'inline-block p-2 bg-blue-600 text-white rounded hover:bg-blue-700';
export const centeredContent = 'bg-gray-100 flex items-center justify-center min-h-screen';
export const container = 'max-w-md mx-auto p-6 bg-white shadow-md rounded-lg';
export const errorText = 'text-red-500 text-sm mt-1';
export const heading = 'text-2xl font-bold mb-4';
export const input = 'w-full p-2 border rounded focus:outline-none focus:ring-2 focus:ring-blue-500';
export const label = 'block text-sm font-medium';
export const link = 'text-blue-600 hover:underline';
export const navbar = 'bg-blue-900 p-2 shadow-md'; // Added for navbar
export const navbarContainer = 'max-w-7xl mx-auto flex items-center justify-between'; // Added for inner layout
export const navbarLink = 'text-white hover:underline'; // Added for navbar links
export const subText = 'text-gray-600 text-sm';
export const successBox = 'mt-4 p-4 bg-green-100 rounded';
export const successText = 'text-green-700';
export const successTextCenter = 'text-green-600 text-center';
export const table = 'min-w-full bg-white border border-gray-200';
export const tableHeader = 'bg-blue-900 text-white';
export const tableHeaderCell = 'py-2 px-4 border-b';
export const tableHeaderCellLeft = 'py-2 px-4 border-b text-left';
export const tableHeaderCellCenter = 'py-2 px-4 border-b text-center';
export const tableRowHover = 'hover:bg-gray-100';
export const tableCell = 'py-2 px-4 border-b';
export const tableCellLeft = 'py-2 px-4 border-b text-left';
export const tableCellCenter = 'py-2 px-4 border-b text-center';
export const text = 'mb-2';
export const wideContainer = 'mx-auto p-6 bg-white shadow-md rounded-lg';