export const buttonGroup = 'flex space-x-2';
export const buttonPrimary = 'w-full p-2 bg-purple-500 text-white rounded-full hover:bg-purple-600 hover:scale-105 transition-all shadow-md';
export const buttonSecondary = 'w-full p-2 bg-blue-400 text-white rounded-full hover:bg-blue-500 hover:scale-105 transition-all shadow-md';
export const centered = 'text-center';
export const centeredButton = 'inline-block p-2 bg-purple-500 text-white rounded-full hover:bg-purple-600 hover:scale-105 transition-all';
export const centeredContent = 'bg-pink-50 flex items-center justify-center min-h-screen';
export const container = 'max-w-md mx-auto p-6 bg-white rounded-xl shadow-lg border border-purple-100';
export const errorText = 'text-red-500 text-sm mt-1';
export const featureCard = 'bg-white p-6 rounded-lg shadow-md text-center'; // Legacy, kept for compatibility
export const featureContainer = 'max-w-4xl mx-auto grid gap-8 md:grid-cols-3'; // Legacy, kept for compatibility
export const featureSection = 'py-12 px-4 bg-gray-100'; // Legacy, kept for compatibility
export const featureText = 'text-gray-600';
export const featureTitle = 'text-xl font-semibold mb-2'; // Legacy, kept for compatibility
export const heading = 'text-2xl font-bold mb-4 text-purple-600';
export const input = 'w-full p-2 border border-blue-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-400 bg-pink-50';
export const kawaiiButton = 'inline-block p-3 bg-purple-500 text-white rounded-full hover:bg-purple-600 hover:scale-105 transition-all shadow-md';
export const kawaiiFeatureCard = 'bg-pink-100 p-6 rounded-xl shadow-md text-center transform hover:scale-105 transition-transform';
export const kawaiiFeatureContainer = 'max-w-5xl mx-auto grid gap-6 md:grid-cols-3';
export const kawaiiFeatureSection = 'py-12 px-4 bg-white';
export const kawaiiFeatureTitle = 'text-xl font-semibold text-blue-600 mb-2';
export const kawaiiFooter = 'py-6 text-center bg-blue-100';
export const kawaiiHeading = 'text-4xl md:text-5xl font-bold text-purple-600 mb-4';
export const kawaiiHero = 'bg-gradient-to-r from-pink-200 to-blue-200 py-16 px-4 text-center rounded-b-xl shadow-lg';
export const kawaiiSubtext = 'text-lg md:text-xl text-gray-700 mb-6';
export const label = 'block text-sm font-medium text-blue-600';
export const link = 'text-purple-500 hover:underline';
export const navbar = 'bg-purple-600 p-2 shadow-md';
export const navbarContainer = 'max-w-7xl mx-auto flex items-center justify-between';
export const navbarLink = 'text-white hover:underline';
export const subText = 'text-gray-600 text-sm';
export const successBox = 'mt-4 p-4 bg-green-100 rounded-xl shadow-md';
export const successText = 'text-green-700';
export const successTextCenter = 'text-green-600 text-center';
export const table = 'min-w-full bg-white border border-purple-100 rounded-xl shadow-md';
export const tableCell = 'py-2 px-4 border-b';
export const tableCellCenter = 'py-2 px-4 border-b text-center';
export const tableCellLeft = 'py-2 px-4 border-b text-left';
export const tableHeader = 'bg-purple-500 text-white';
export const tableHeaderCell = 'py-2 px-4 border-b';
export const tableHeaderCellCenter = 'py-2 px-4 border-b text-center';
export const tableHeaderCellLeft = 'py-2 px-4 border-b text-left';
export const tableRowHover = 'hover:bg-pink-50';
export const text = 'mb-2 text-gray-700';
export const wideContainer = 'mx-auto p-6 bg-white rounded-xl shadow-lg border border-purple-100';